Improve command-line auto completion

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -17,25 +17,26 @@ app_dir=/usr/local/dotfiles
 user_uid=$(id -u)
 user_gid=$(id -g)
 
-arg_debug=$(echo "$*" | grep -o -- "--debug"); [ -n "$arg_debug" ] && set -x
-arg_update=$(echo "$*" | grep -o -- "--update-os")
-arg_install=$(echo "$*" | grep -o -- "--install")
-arg_install_apps=$(echo "$*" | grep -o -- "--install=[-_,A-Za-z0-9]*" | sed "s/--install=//")
-arg_config=$(echo "$*" | grep -o -- "--config")
 arg_config_apps=$(echo "$*" | grep -o -- "--config=[-_,A-Za-z0-9]*" | sed "s/--config=//")
+arg_config=$(echo "$*" | grep -o -- "--config")
 arg_customise=$(echo "$*" | grep -o -- "--customise")
-arg_minimal=$(echo "$*" | grep -o -- "--minimal")
-arg_synchronise_only=$(echo "$*" | grep -o -- "--synchronise-only")
+arg_debug=$(echo "$*" | grep -o -- "--debug"); [ -n "$arg_debug" ] && set -x
+arg_directory=$(echo "$*" | grep -Eo -- "--directory=[-_A-Za-z0-9/]+" | sed "s/--directory=//")
+arg_extension_man=$(echo "$*" | grep -o -- "--extension-man")
+arg_fix_file_ownership=$(echo "$*" | grep -o -- "--fix-file-ownership")
 arg_force_download=$(echo "$*" | grep -o -- "--force-download")
 arg_force_initialise=$(echo "$*" | grep -o -- "--force-initialise")
-arg_directory=$(echo "$*" | grep -Eo -- "--directory=[-_A-Za-z0-9/]+" | sed "s/--directory=//")
-arg_user=$(echo "$*" | grep -Eo -- "--user=[-_A-Za-z0-9/]+" | sed "s/--user=//")
-arg_load_secrets=$(echo "$*" | grep -o -- "--load-secrets")
-arg_extension_man=$(echo "$*" | grep -o -- "--extension-man")
-arg_sudo=$(echo "$*" | grep -o -- "--sudo")
-arg_test=$(echo "$*" | grep -o -- "--test")
-arg_offline=$(echo "$*" | grep -o -- "--offline")
 arg_help=$(echo "$*" | grep -o -- "--help")
+arg_install_apps=$(echo "$*" | grep -o -- "--install=[-_,A-Za-z0-9]*" | sed "s/--install=//")
+arg_install=$(echo "$*" | grep -o -- "--install")
+arg_load_secrets=$(echo "$*" | grep -o -- "--load-secrets")
+arg_minimal=$(echo "$*" | grep -o -- "--minimal")
+arg_offline=$(echo "$*" | grep -o -- "--offline")
+arg_sudo=$(echo "$*" | grep -o -- "--sudo")
+arg_synchronise_only=$(echo "$*" | grep -o -- "--synchronise-only")
+arg_test=$(echo "$*" | grep -o -- "--test")
+arg_update=$(echo "$*" | grep -o -- "--update-os")
+arg_user=$(echo "$*" | grep -Eo -- "--user=[-_A-Za-z0-9/]+" | sed "s/--user=//")
 
 install_already_processed=""
 config_already_processed=""
@@ -231,24 +232,27 @@ function dotfiles_setup {
     fi
 
     print_h1 "Finalising..."
+
     # set correct file ownership
-    [ -z "$arg_user" ] && sudo chown -R $user_uid:$user_gid $DIR 2>/dev/null ||:
-    [ -n "$arg_user" ] && sudo chown -R $arg_user:$arg_user $DIR 2>/dev/null ||:
+    if [ -n "$arg_fix_file_ownership" ]; then
+        [ -z "$arg_user" ] && sudo chown -R $user_uid:$user_gid $DIR 2>/dev/null ||:
+        [ -n "$arg_user" ] && sudo chown -R $arg_user:$arg_user $DIR 2>/dev/null ||:
+    fi
 }
 
 function dotfiles_shell {
 
     rm -f $DIR/etc/profile.d/dotfiles-config
-    echo "export USER_NAME=\"$USER_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export USER_EMAIL=\"$USER_EMAIL\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export GITHUB_ACCOUNT=\"$GITHUB_ACCOUNT\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export BITBUCKET_ACCOUNT=\"$BITBUCKET_ACCOUNT\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export BASH_PROMPT_SHOW_GIT=\"$BASH_PROMPT_SHOW_GIT\"" >> $DIR/etc/profile.d/dotfiles-config
     echo "export BASH_PROMPT_RELOAD_HISTORY=\"$BASH_PROMPT_RELOAD_HISTORY\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export GIT_AUTHOR_NAME=\"\$USER_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
-    echo "export GIT_COMMITTER_NAME=\"\$GIT_AUTHOR_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export BASH_PROMPT_SHOW_GIT=\"$BASH_PROMPT_SHOW_GIT\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export BITBUCKET_ACCOUNT=\"$BITBUCKET_ACCOUNT\"" >> $DIR/etc/profile.d/dotfiles-config
     echo "export GIT_AUTHOR_EMAIL=\"\$USER_EMAIL\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export GIT_AUTHOR_NAME=\"\$USER_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
     echo "export GIT_COMMITTER_EMAIL=\"\$GIT_AUTHOR_EMAIL\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export GIT_COMMITTER_NAME=\"\$GIT_AUTHOR_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export GITHUB_ACCOUNT=\"$GITHUB_ACCOUNT\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export USER_EMAIL=\"$USER_EMAIL\"" >> $DIR/etc/profile.d/dotfiles-config
+    echo "export USER_NAME=\"$USER_NAME\"" >> $DIR/etc/profile.d/dotfiles-config
 }
 
 function os_common {
@@ -589,31 +593,32 @@ function usage {
     local file=$(basename $0 2> /dev/null)
     printf "\nUsage: ${file} [options]\n"
     printf "\nOptions:\n"
-    printf "\t--update-os\n"
-    printf "\t--install={dependencies|system|admin|developer|user}-bundle|all-bundles,app1,app2,...\n"
     printf "\t--config[=all,app1,app2,...]\n"
     printf "\t--customise\n"
-    printf "\t--minimal\n"
-    printf "\t--synchronise-only\n"
+    printf "\t--debug\n"
+    printf "\t--directory=/dir\n"
+    printf "\t--extension-man\n"
+    printf "\t--fix-file-ownership\n"
     printf "\t--force-download\n"
     printf "\t--force-initialise\n"
-    printf "\t--directory=/dir\n"
-    printf "\t--user=username\n"
-    printf "\t--load-secrets\n"
-    printf "\t--extension-man\n"
-    printf "\t--sudo\n"
-    printf "\t--test\n"
-    printf "\t--debug\n"
-    printf "\t--offline\n"
     printf "\t--help\n"
+    printf "\t--install={dependencies|system|admin|developer|user}-bundle|all-bundles,app1,app2,...\n"
+    printf "\t--load-secrets\n"
+    printf "\t--minimal\n"
+    printf "\t--offline\n"
+    printf "\t--sudo\n"
+    printf "\t--synchronise-only\n"
+    printf "\t--test\n"
+    printf "\t--update-os\n"
+    printf "\t--user=username\n"
     printf "\nVariables:\n"
-    printf "\tUSER_NAME=\"User Name\" (required)\n"
-    printf "\tUSER_EMAIL=user@email (required)\n"
+    printf "\tBASH_PROMPT_RELOAD_HISTORY=true|yes|on|1|TRUE|YES|ON (default: no)\n"
+    printf "\tBASH_PROMPT_SHOW_GIT=true|yes|on|1|TRUE|YES|ON (default: yes)\n"
+    printf "\tBITBUCKET_ACCOUNT=name\n"
     printf "\tGITHUB_ACCOUNT=name\n"
     printf "\tGITLAB_ACCOUNT=name\n"
-    printf "\tBITBUCKET_ACCOUNT=name\n"
-    printf "\tBASH_PROMPT_SHOW_GIT=true|yes|on|1|TRUE|YES|ON (default: yes)\n"
-    printf "\tBASH_PROMPT_RELOAD_HISTORY=true|yes|on|1|TRUE|YES|ON (default: no)\n"
+    printf "\tUSER_EMAIL=user@email (required)\n"
+    printf "\tUSER_NAME=\"User Name\" (required)\n"
     printf "\n"
 }
 
diff --git a/etc/profile.d/completion-bash b/etc/profile.d/completion-bash
--- a/etc/profile.d/completion-bash
+++ b/etc/profile.d/completion-bash
@@ -1,15 +1,16 @@
 #!/bin/bash
 
 # SOURCE: https://github.com/scop/bash-completion/blob/master/bash_completion
-# COMMIT: b10236717bae7e1a072031fa9cbf0006b66b4057
-#  PATCH: lines 2094-2108
+# COMMIT: c263a3fc8ca098cb42eab88026e1ffa2fa809ec0
+#   DATE: 2018/12/06
+#  PATCH: lines 2100-2114
 
 #                                                          -*- shell-script -*-
 #
 #   bash_completion - programmable completion functions for bash 4.1+
 #
 #   Copyright © 2006-2008, Ian Macdonald <ian@caliban.org>
-#             © 2009-2017, Bash Completion Maintainers
+#             © 2009-2018, Bash Completion Maintainers
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -29,7 +30,7 @@
 #
 #   https://github.com/scop/bash-completion
 
-BASH_COMPLETION_VERSINFO=(2 7)
+BASH_COMPLETION_VERSINFO=(2 8)
 
 if [[ $- == *v* ]]; then
     BASH_COMPLETION_ORIGINAL_V_VALUE="-v"
@@ -559,12 +560,11 @@ _filedir()
     _tilde "$cur" || return
 
     local -a toks
-    local x tmp
+    local x reset
 
-    x=$( compgen -d -- "$cur" ) &&
-    while read -r tmp; do
-        toks+=( "$tmp" )
-    done <<< "$x"
+    reset=$(shopt -po noglob); set -o noglob
+    toks=( $( compgen -d -- "$cur" ) )
+    IFS=' '; $reset; IFS=$'\n'
 
     if [[ "$1" != -d ]]; then
         local quoted
@@ -573,17 +573,16 @@ _filedir()
         # Munge xspec to contain uppercase version too
         # http://thread.gmane.org/gmane.comp.shells.bash.bugs/15294/focus=15306
         local xspec=${1:+"!*.@($1|${1^^})"}
-        x=$( compgen -f -X "$xspec" -- $quoted ) &&
-        while read -r tmp; do
-            toks+=( "$tmp" )
-        done <<< "$x"
+        reset=$(shopt -po noglob); set -o noglob
+        toks+=( $( compgen -f -X "$xspec" -- $quoted ) )
+        IFS=' '; $reset; IFS=$'\n'
 
         # Try without filter if it failed to produce anything and configured to
-        [[ -n ${COMP_FILEDIR_FALLBACK:-} && -n "$1" && ${#toks[@]} -lt 1 ]] && \
-            x=$( compgen -f -- $quoted ) &&
-            while read -r tmp; do
-                toks+=( "$tmp" )
-            done <<< "$x"
+        [[ -n ${COMP_FILEDIR_FALLBACK:-} && -n "$1" && ${#toks[@]} -lt 1 ]] && {
+            reset=$(shopt -po noglob); set -o noglob
+            toks+=( $( compgen -f -- $quoted ) )
+            IFS=' '; $reset; IFS=$'\n'
+        }
     fi
 
     if [[ ${#toks[@]} -ne 0 ]]; then
@@ -920,15 +919,23 @@ _configured_interfaces()
 }
 
 # Local IP addresses.
+# -4: IPv4 addresses only (default)
+# -6: IPv6 addresses only
+# -a: All addresses
 #
 _ip_addresses()
 {
+    local n
+    case $1 in
+        -a) n='6\?' ;;
+        -6) n='6' ;;
+    esac
     local PATH=$PATH:/sbin
-    COMPREPLY+=( $( compgen -W \
-        "$( { LC_ALL=C ifconfig -a || ip addr show; } 2>/dev/null | command sed -ne \
+    local addrs=$( { LC_ALL=C ifconfig -a || ip addr show; } 2>/dev/null |
+        command sed -ne \
             's/.*addr:\([^[:space:]]*\).*/\1/p' -ne \
-            's|.*inet[[:space:]]\{1,\}\([^[:space:]/]*\).*|\1|p' )" \
-        -- "$cur" ) )
+            "s|.*inet$n[[:space:]]\{1,\}\([^[:space:]/]*\).*|\1|p" )
+    COMPREPLY+=( $( compgen -W "$addrs" -- "$cur" ) )
 }
 
 # This function completes on available kernels
@@ -944,18 +951,19 @@ _kernel_versions()
 #
 _available_interfaces()
 {
-    local cmd PATH=$PATH:/sbin
+    local PATH=$PATH:/sbin
 
-    if [[ ${1:-} == -w ]]; then
-        cmd="iwconfig"
-    elif [[ ${1:-} == -a ]]; then
-        cmd="{ ifconfig || ip link show up; }"
-    else
-        cmd="{ ifconfig -a || ip link show; }"
-    fi
-
-    COMPREPLY=( $( eval $cmd 2>/dev/null | awk \
+    COMPREPLY=( $( {
+        if [[ ${1:-} == -w ]]; then
+            iwconfig
+        elif [[ ${1:-} == -a ]]; then
+            ifconfig || ip link show up
+        else
+            ifconfig -a || ip link show
+        fi
+    } 2>/dev/null | awk \
         '/^[^ \t]/ { if ($1 ~ /^[0-9]+:/) { print $2 } else { print $1 } }' ) )
+
     COMPREPLY=( $( compgen -W '${COMPREPLY[@]/%[[:punct:]]/}' -- "$cur" ) )
 }
 
@@ -1010,21 +1018,8 @@ _tilde()
 # @param $1  Name of variable (not the value of the variable) to expand
 __expand_tilde_by_ref()
 {
-    # Does $1 start with tilde (~)?
     if [[ ${!1} == \~* ]]; then
-        # Does $1 contain slash (/)?
-        if [[ ${!1} == */* ]]; then
-            # Yes, $1 contains slash;
-            # 1: Remove * including and after first slash (/), i.e. "~a/b"
-            #    becomes "~a".  Double quotes allow eval.
-            # 2: Remove * before the first slash (/), i.e. "~a/b"
-            #    becomes "b".  Single quotes prevent eval.
-            #       +-----1----+ +---2----+
-            eval $1="${!1/%\/*}"/'${!1#*/}'
-        else
-            # No, $1 doesn't contain slash
-            eval $1="${!1}"
-        fi
+        eval $1=$(printf ~%q "${!1#\~}")
     fi
 } # __expand_tilde_by_ref()
 
@@ -1033,19 +1028,14 @@ __expand_tilde_by_ref()
 #
 _expand()
 {
-    # FIXME: Why was this here?
-    #[ "$cur" != "${cur%\\}" ] && cur+="\\"
-
     # Expand ~username type directory specifications.  We want to expand
     # ~foo/... to /home/foo/... to avoid problems when $cur starting with
     # a tilde is fed to commands and ending up quoted instead of expanded.
 
     if [[ "$cur" == \~*/* ]]; then
-        eval cur=$cur 2>/dev/null
+        __expand_tilde_by_ref cur
     elif [[ "$cur" == \~* ]]; then
-        cur=${cur#\~}
-        COMPREPLY=( $( compgen -P '~' -u -- "$cur" ) )
-        [[ ${#COMPREPLY[@]} -eq 1 ]] && eval COMPREPLY[0]=${COMPREPLY[0]}
+        _tilde "$cur" || eval COMPREPLY[0]=$(printf ~%q "${COMPREPLY[0]#\~}")
         return ${#COMPREPLY[@]}
     fi
 }
@@ -1162,7 +1152,8 @@ _services()
         $( printf '%s\n' ${sysvdirs[0]}/!($_backup_glob|functions|README) ) )
     $reset
 
-    COMPREPLY+=( $( systemctl list-units --full --all 2>/dev/null | \
+    COMPREPLY+=( $( { systemctl list-units --full --all || \
+                      systemctl list-unit-files; } 2>/dev/null | \
         awk '$1 ~ /\.service$/ { sub("\\.service$", "", $1); print $1 }' ) )
 
     if [[ -x /sbin/upstart-udev-bridge ]]; then
@@ -1371,14 +1362,17 @@ _get_first_arg()
 # This function counts the number of args, excluding options
 # @param $1 chars  Characters out of $COMP_WORDBREAKS which should
 #     NOT be considered word breaks. See __reassemble_comp_words_by_ref.
+# @param $2 glob   Options whose following argument should not be counted
 _count_args()
 {
     local i cword words
     __reassemble_comp_words_by_ref "$1" words cword
 
     args=1
-    for i in "${words[@]:1:cword-1}"; do
-        [[ "$i" != -* ]] && args=$(($args+1))
+    for (( i=1; i < cword; i++ )); do
+        if [[ ${words[i]} != -* && ${words[i-1]} != $2 ]]; then
+           args=$(($args+1))
+        fi
     done
 }
 
@@ -1505,9 +1499,9 @@ _included_ssh_config_files()
 # Return: Completions, starting with CWORD, are added to COMPREPLY[]
 _known_hosts_real()
 {
-    local configfile flag prefix
-    local cur curd awkcur user suffix aliases i host ipv4 ipv6
-    local -a kh khd config
+    local configfile flag prefix OIFS=$IFS
+    local cur user suffix aliases i host ipv4 ipv6
+    local -a kh tmpkh khd config
 
     # TODO remove trailing %foo from entries
 
@@ -1546,8 +1540,7 @@ _known_hosts_real()
 
     # Known hosts files from configs
     if [[ ${#config[@]} -gt 0 ]]; then
-        local OIFS=$IFS IFS=$'\n' j
-        local -a tmpkh
+        local IFS=$'\n' j
         # expand paths (if present) to global and user known hosts files
         # TODO(?): try to make known hosts files with more than one consecutive
         #          spaces in their name work (watch out for ~ expansion
@@ -1584,35 +1577,31 @@ _known_hosts_real()
 
     # If we have known_hosts files to use
     if [[ ${#kh[@]} -gt 0 || ${#khd[@]} -gt 0 ]]; then
-        # Escape slashes and dots in paths for awk
-        awkcur=${cur//\//\\\/}
-        awkcur=${awkcur//\./\\\.}
-        curd=$awkcur
-
-        if [[ "$awkcur" == [0-9]*[.:]* ]]; then
-            # Digits followed by a dot or a colon - just search for that
-            awkcur="^$awkcur[.:]*"
-        elif [[ "$awkcur" == [0-9]* ]]; then
-            # Digits followed by no dot or colon - search for digits followed
-            # by a dot or a colon
-            awkcur="^$awkcur.*[.:]"
-        elif [[ -z $awkcur ]]; then
-            # A blank - search for a dot, a colon, or an alpha character
-            awkcur="[a-z.:]"
-        else
-            awkcur="^$awkcur"
-        fi
-
         if [[ ${#kh[@]} -gt 0 ]]; then
-            # FS needs to look for a comma separated list
-            COMPREPLY+=( $( awk 'BEGIN {FS=","}
-            /^\s*[^|\#]/ {
-            sub("^@[^ ]+ +", ""); \
-            sub(" .*$", ""); \
-            for (i=1; i<=NF; ++i) { \
-            sub("^\\[", "", $i); sub("\\](:[0-9]+)?$", "", $i); \
-            if ($i !~ /[*?]/ && $i ~ /'"$awkcur"'/) {print $i} \
-            }}' "${kh[@]}" 2>/dev/null ) )
+            # https://man.openbsd.org/sshd.8#SSH_KNOWN_HOSTS_FILE_FORMAT
+            for i in "${kh[@]}"; do
+                while read -ra tmpkh; do
+                    set -- "${tmpkh[@]}"
+                    # Skip entries starting with | (hashed) and # (comment)
+                    [[ $1 == [\|\#]* ]] && continue
+                    # Ignore leading @foo (markers)
+                    [[ $1 == @* ]] && shift
+                    # Split entry on commas
+                    local IFS=,
+                    for host in $1; do
+                        # Skip hosts containing wildcards
+                        [[ $host == *[*?]* ]] && continue
+                        # Remove leading [
+                        host="${host#[}"
+                        # Remove trailing ] + optional :port
+                        host="${host%]?(:+([0-9]))}"
+                        # Add host to candidates
+                        COMPREPLY+=( $host )
+                    done
+                    IFS=$OIFS
+                done < "$i"
+            done
+            COMPREPLY=( $( compgen -W '${COMPREPLY[@]}' -- "$cur" ) )
         fi
         if [[ ${#khd[@]} -gt 0 ]]; then
             # Needs to look for files called
@@ -1620,7 +1609,7 @@ _known_hosts_real()
             # dont fork any processes, because in a cluster environment,
             # there can be hundreds of hostkeys
             for i in "${khd[@]}" ; do
-                if [[ "$i" == *key_22_$curd*.pub && -r "$i" ]]; then
+                if [[ "$i" == *key_22_$cur*.pub && -r "$i" ]]; then
                     host=${i/#*key_22_/}
                     host=${host/%.pub/}
                     COMPREPLY+=( $host )
@@ -1681,7 +1670,7 @@ _known_hosts_real()
     __ltrim_colon_completions "$prefix$user$cur"
 
 } # _known_hosts_real()
-complete -F _known_hosts traceroute traceroute6 tracepath tracepath6 \
+complete -F _known_hosts traceroute traceroute6 \
     fping fping6 telnet rsh rlogin ftp dig mtr ssh-installkeys showmount
 
 # This meta-cd function observes the CDPATH variable, so that cd additionally
@@ -1898,9 +1887,10 @@ _longopt()
             command sed -ne 's/.*\(--[-A-Za-z0-9]\{1,\}=\{0,1\}\).*/\1/p' | sort -u )" \
             -- "$cur" ) )
         [[ $COMPREPLY == *= ]] && compopt -o nospace
-    elif [[ "$1" == @(@(mk|rm)dir|chroot) ]]; then
+    elif [[ "$1" == @(rmdir|chroot) ]]; then
         _filedir -d
     else
+        [[ "$1" == mkdir ]] && compopt -o nospace
         _filedir
     fi
 }
@@ -1912,7 +1902,13 @@ complete -F _longopt a2ps awk base64 bash bc bison cat chroot colordiff cp \
     sed seq sha{,1,224,256,384,512}sum shar sort split strip sum tac tail tee \
     texindex touch tr uname unexpand uniq units vdir wc who
 
-declare -A _xspecs
+# declare only knows -g in bash >= 4.2.
+if [[ ${BASH_VERSINFO[0]} -gt 4 ||
+      ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -ge 2 ]]; then
+    declare -Ag _xspecs
+else
+    declare -A _xspecs
+fi
 _filedir_xspec()
 {
     local cur prev words cword
@@ -1949,6 +1945,13 @@ _filedir_xspec()
         }
         ))
 
+    # Try without filter if it failed to produce anything and configured to
+    [[ -n ${COMP_FILEDIR_FALLBACK:-} && ${#toks[@]} -lt 1 ]] && {
+        local reset=$(shopt -po noglob); set -o noglob
+        toks+=( $( compgen -f -- "$(quote_readline "$cur")" ) )
+        IFS=' '; $reset; IFS=$'\n'
+    }
+
     if [[ ${#toks[@]} -ne 0 ]]; then
         compopt -o filenames
         COMPREPLY=( "${toks[@]}" )
@@ -1962,11 +1965,10 @@ _install_xspec()
     for cmd in $@; do
         _xspecs[$cmd]=$xspec
     done
-    complete -F _filedir_xspec $@
 }
 # bzcmp, bzdiff, bz*grep, bzless, bzmore intentionally not here, see Debian: #455510
 _install_xspec '!*.?(t)bz?(2)' bunzip2 bzcat pbunzip2 pbzcat lbunzip2 lbzcat
-_install_xspec '!*.@(zip|[egjsw]ar|exe|pk3|wsz|zargo|xpi|s[tx][cdiw]|sx[gm]|o[dt][tspgfc]|od[bm]|oxt|epub|apk|ipa|do[ct][xm]|p[op]t[mx]|xl[st][xm]|pyz)' unzip zipinfo
+_install_xspec '!*.@(zip|[egjswx]ar|exe|pk3|wsz|zargo|xpi|s[tx][cdiw]|sx[gm]|o[dt][tspgfc]|od[bm]|oxt|epub|apk|ipa|do[ct][xm]|p[op]t[mx]|xl[st][xm]|pyz|whl)' unzip zipinfo
 _install_xspec '*.Z' compress znew
 # zcmp, zdiff, z*grep, zless, zmore intentionally not here, see Debian: #455510
 _install_xspec '!*.@(Z|[gGd]z|t[ag]z)' gunzip zcat
@@ -1984,15 +1986,15 @@ _install_xspec '!*.@(dvi|DVI)?(.@(gz|Z|bz2))' xdvi kdvi
 _install_xspec '!*.dvi' dvips dviselect dvitype dvipdf advi dvipdfm dvipdfmx
 _install_xspec '!*.[pf]df' acroread gpdf xpdf
 _install_xspec '!*.@(?(e)ps|pdf)' kpdf
-_install_xspec '!*.@(okular|@(?(e|x)ps|?(E|X)PS|[pf]df|[PF]DF|dvi|DVI|cb[rz]|CB[RZ]|djv?(u)|DJV?(U)|dvi|DVI|gif|jp?(e)g|miff|tif?(f)|pn[gm]|p[bgp]m|bmp|xpm|ico|xwd|tga|pcx|GIF|JP?(E)G|MIFF|TIF?(F)|PN[GM]|P[BGP]M|BMP|XPM|ICO|XWD|TGA|PCX|epub|EPUB|odt|ODT|fb?(2)|FB?(2)|mobi|MOBI|g3|G3|chm|CHM)?(.?(gz|GZ|bz2|BZ2)))' okular
+_install_xspec '!*.@(okular|@(?(e|x)ps|?(E|X)PS|[pf]df|[PF]DF|dvi|DVI|cb[rz]|CB[RZ]|djv?(u)|DJV?(U)|dvi|DVI|gif|jp?(e)g|miff|tif?(f)|pn[gm]|p[bgp]m|bmp|xpm|ico|xwd|tga|pcx|GIF|JP?(E)G|MIFF|TIF?(F)|PN[GM]|P[BGP]M|BMP|XPM|ICO|XWD|TGA|PCX|epub|EPUB|odt|ODT|fb?(2)|FB?(2)|mobi|MOBI|g3|G3|chm|CHM)?(.?(gz|GZ|bz2|BZ2|xz|XZ)))' okular
 _install_xspec '!*.pdf' epdfview pdfunite
 _install_xspec '!*.@(cb[rz7t]|djv?(u)|?(e)ps|pdf)' zathura
 _install_xspec '!*.@(?(e)ps|pdf)' ps2pdf ps2pdf12 ps2pdf13 ps2pdf14 ps2pdfwr
 _install_xspec '!*.texi*' makeinfo texi2html
 _install_xspec '!*.@(?(la)tex|texi|dtx|ins|ltx|dbj)' tex latex slitex jadetex pdfjadetex pdftex pdflatex texi2dvi xetex xelatex luatex lualatex
 _install_xspec '!*.mp3' mpg123 mpg321 madplay
-_install_xspec '!*@(.@(mp?(e)g|MP?(E)G|wm[av]|WM[AV]|avi|AVI|asf|vob|VOB|bin|dat|divx|DIVX|vcd|ps|pes|fli|flv|FLV|fxm|FXM|viv|rm|ram|yuv|mov|MOV|qt|QT|web[am]|WEB[AM]|mp[234]|MP[234]|m?(p)4[av]|M?(P)4[AV]|mkv|MKV|og[agmv]|OG[AGMV]|t[ps]|T[PS]|m2t?(s)|M2T?(S)|mts|MTS|wav|WAV|flac|FLAC|asx|ASX|mng|MNG|srt|m[eo]d|M[EO]D|s[3t]m|S[3T]M|it|IT|xm|XM)|+([0-9]).@(vdr|VDR))?(.part)' xine aaxine fbxine
-_install_xspec '!*@(.@(mp?(e)g|MP?(E)G|wm[av]|WM[AV]|avi|AVI|asf|vob|VOB|bin|dat|divx|DIVX|vcd|ps|pes|fli|flv|FLV|fxm|FXM|viv|rm|ram|yuv|mov|MOV|qt|QT|web[am]|WEB[AM]|mp[234]|MP[234]|m?(p)4[av]|M?(P)4[AV]|mkv|MKV|og[agmv]|OG[AGMV]|t[ps]|T[PS]|m2t?(s)|M2T?(S)|mts|MTS|wav|WAV|flac|FLAC|asx|ASX|mng|MNG|srt|m[eo]d|M[EO]D|s[3t]m|S[3T]M|it|IT|xm|XM|iso|ISO)|+([0-9]).@(vdr|VDR))?(.part)' kaffeine dragon
+_install_xspec '!*@(.@(mp?(e)g|MP?(E)G|wm[av]|WM[AV]|avi|AVI|asf|vob|VOB|bin|dat|divx|DIVX|vcd|ps|pes|fli|flv|FLV|fxm|FXM|viv|rm|ram|yuv|mov|MOV|qt|QT|web[am]|WEB[AM]|mp[234]|MP[234]|m?(p)4[av]|M?(P)4[AV]|mkv|MKV|og[agmv]|OG[AGMV]|t[ps]|T[PS]|m2t?(s)|M2T?(S)|mts|MTS|wav|WAV|flac|FLAC|asx|ASX|mng|MNG|srt|m[eo]d|M[EO]D|s[3t]m|S[3T]M|it|IT|xm|XM)|+([0-9]).@(vdr|VDR))?(.@(crdownload|part))' xine aaxine fbxine
+_install_xspec '!*@(.@(mp?(e)g|MP?(E)G|wm[av]|WM[AV]|avi|AVI|asf|vob|VOB|bin|dat|divx|DIVX|vcd|ps|pes|fli|flv|FLV|fxm|FXM|viv|rm|ram|yuv|mov|MOV|qt|QT|web[am]|WEB[AM]|mp[234]|MP[234]|m?(p)4[av]|M?(P)4[AV]|mkv|MKV|og[agmv]|OG[AGMV]|t[ps]|T[PS]|m2t?(s)|M2T?(S)|mts|MTS|wav|WAV|flac|FLAC|asx|ASX|mng|MNG|srt|m[eo]d|M[EO]D|s[3t]m|S[3T]M|it|IT|xm|XM|iso|ISO)|+([0-9]).@(vdr|VDR))?(.@(crdownload|part))' kaffeine dragon
 _install_xspec '!*.@(avi|asf|wmv)' aviplay
 _install_xspec '!*.@(rm?(j)|ra?(m)|smi?(l))' realplay
 _install_xspec '!*.@(mpg|mpeg|avi|mov|qt)' xanim
@@ -2006,7 +2008,6 @@ _install_xspec '*.@([ao]|so|so.!(conf|*/*)|[rs]pm|gif|jp?(e)g|mp3|mp?(e)g|avi|as
 _install_xspec '!*.@(zip|z|gz|tgz)' bzme
 # konqueror not here on purpose, it's more than a web/html browser
 _install_xspec '!*.@(?([xX]|[sS])[hH][tT][mM]?([lL]))' netscape mozilla lynx galeon dillo elinks amaya epiphany
-_install_xspec '!*.@(?([xX]|[sS])[hH][tT][mM]?([lL])|[pP][dD][fF])' firefox mozilla-firefox iceweasel google-chrome chromium-browser
 _install_xspec '!*.@(sxw|stw|sxg|sgl|doc?([mx])|dot?([mx])|rtf|txt|htm|html|?(f)odt|ott|odm|pdf)' oowriter lowriter
 _install_xspec '!*.@(sxi|sti|pps?(x)|ppt?([mx])|pot?([mx])|?(f)odp|otp)' ooimpress loimpress
 _install_xspec '!*.@(sxc|stc|xls?([bmx])|xlw|xlt?([mx])|[ct]sv|?(f)ods|ots)' oocalc localc
@@ -2040,7 +2041,8 @@ complete -F _minimal ''
 __load_completion()
 {
     local -a dirs=( ${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions )
-    local OIFS=$IFS IFS=: dir cmd="$1" compfile
+    local OIFS=$IFS IFS=: dir cmd="${1##*/}" compfile
+    [[ -n $cmd ]] || return 1
     for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}; do
         dirs+=( $dir/bash-completion/completions )
     done
@@ -2053,12 +2055,16 @@ __load_completion()
     fi
 
     for dir in "${dirs[@]}"; do
-        for compfile in "${cmd##*/}" "${cmd##*/}".bash _"${cmd##*/}"; do
+        [[ -d "$dir" ]] || continue
+        for compfile in "$cmd" "$cmd.bash" "_$cmd"; do
             compfile="$dir/$compfile"
             # Avoid trying to source dirs; https://bugzilla.redhat.com/903540
             [[ -f "$compfile" ]] && . "$compfile" &>/dev/null && return 0
         done
     done
+
+    # Look up simple "xspec" completions
+    [[ "${_xspecs[$cmd]}" ]] && complete -F _filedir_xspec "$cmd" && return 0
 
     return 1
 }
@@ -2100,7 +2106,7 @@ _xfunc()
 #     done
 # fi
 # unset compat_dir i _blacklist_glob
-
+#
 # # source user completion file
 # user_completion=${BASH_COMPLETION_USER_FILE:-~/.bash_completion}
 # [[ ${BASH_SOURCE[0]} != $user_completion && -r $user_completion ]] \
